CREATE TABLE IF NOT EXISTS knowledge_packs (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    version TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL,
    applicable_task_types TEXT NOT NULL DEFAULT '[]',
    rules TEXT NOT NULL DEFAULT '[]',
    examples TEXT NOT NULL DEFAULT '[]',
    anti_patterns TEXT NOT NULL DEFAULT '[]',
    validation_hints TEXT NOT NULL DEFAULT '[]',
    priority INTEGER NOT NULL DEFAULT 0,
    enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_knowledge_packs_enabled_priority
    ON knowledge_packs(enabled, priority DESC, name ASC);
CREATE INDEX IF NOT EXISTS idx_knowledge_packs_category
    ON knowledge_packs(category, enabled);

INSERT OR IGNORE INTO knowledge_packs
    (id, name, version, description, category, applicable_task_types, rules, examples,
     anti_patterns, validation_hints, priority, enabled, updated_at)
VALUES
    ('filemaker-xml-core', 'FileMaker XML Core', '1.0.0',
     'FileMaker Clipboard XML全体で共通となる構造知識。', 'xml',
     '["script","script_step","table","field","value_list","layout_object","relationship_design"]',
     '["Clipboard XMLはfmxmlsnippetをルートとし、対象形式に対応するFileMakerオブジェクトを保持する。","属性名・要素名・真偽値の大文字小文字を保持する。"]',
     '["<fmxmlsnippet type=\"FMObjectList\">...</fmxmlsnippet>"]',
     '["一般的なXMLとして妥当であることだけをペースト可能性の根拠にする。"]',
     '["対象のClipboard形式とルート直下のオブジェクト種別を照合する。"]',
     100, 1, datetime('now')),
    ('fmxmlsnippet-core', 'fmxmlsnippet', '1.0.0',
     'FileMakerへペースト可能なfmxmlsnippet wrapperの規則。', 'xml',
     '["script","script_step","table","field","value_list","layout_object"]',
     '["ルート要素はfmxmlsnippetとする。","type属性はFMObjectListを使用する。"]',
     '["<fmxmlsnippet type=\"FMObjectList\"><Step ... /></fmxmlsnippet>"]',
     '["説明文やMarkdownをfmxmlsnippet内部へ混在させる。"]',
     '["ルート要素、type属性、対象オブジェクト数を確認する。"]',
     95, 1, datetime('now')),
    ('table-definition', 'Table Definition', '1.0.0',
     'FileMakerテーブル定義を生成・検証するための知識。', 'schema',
     '["table","database_design"]',
     '["既存テーブルと名前が衝突しないことを確認する。","主キーと監査フィールドの方針を明示する。"]',
     '["患者テーブルにUUID主キー、作成日時、更新日時を定義する。"]',
     '["用途の異なるエンティティを単一テーブルへ詰め込む。"]',
     '["テーブル名、主キー、関連先、既存Projectとの重複を確認する。"]',
     80, 1, datetime('now')),
    ('field-definition', 'Field Definition', '1.0.0',
     'FileMakerフィールド定義と型・オプションの知識。', 'schema',
     '["field","table","database_design"]',
     '["フィールド用途に適したFileMakerデータ型を選択する。","計算・自動入力・索引設定を区別する。"]',
     '["主キーはテキスト型UUIDの自動入力として設計する。"]',
     '["表示用ラベルをそのまま不安定なフィールド名に使用する。"]',
     '["型、自動入力、計算結果型、索引、必須制約を確認する。"]',
     78, 1, datetime('now')),
    ('script-rules', 'Script', '1.0.0',
     'FileMakerスクリプト全体の設計とClipboard XML規則。', 'script',
     '["script","automation","debug"]',
     '["XMSCではScriptをfmxmlsnippet直下へ配置する。","既存処理、エラー処理、トランザクション境界を保持する。"]',
     '["Script要素にname、idおよびFileMakerが要求する属性を設定する。"]',
     '["依頼されていない既存Stepを削除する。"]',
     '["Script wrapper、Step順序、分岐とLoopの対応を確認する。"]',
     90, 1, datetime('now')),
    ('script-step-rules', 'Script Step', '1.0.0',
     'FileMakerスクリプトステップの生成・検証規則。', 'script',
     '["script","script_step","automation","debug"]',
     '["XMSSではStepをfmxmlsnippet直下へ平坦な順序で配置する。","各Stepのenable、id、nameをFileMaker形式で保持する。"]',
     '["<Step enable=\"True\" id=\"1\" name=\"変数を設定\">...</Step>"]',
     '["存在しないStep名や独自属性を推測で追加する。"]',
     '["Step名、Step ID、必須子要素、開始・終了Stepの対応を確認する。"]',
     92, 1, datetime('now')),
    ('calculation-rules', 'Calculation', '1.0.0',
     'FileMaker計算式の生成と参照整合性の知識。', 'calculation',
     '["calculation","script","script_step","field"]',
     '["フィールド参照と変数スコープを区別する。","FileMaker関数名と引数構造を保持する。"]',
     '["JSONGetElement ( $json ; \"data\" )"]',
     '["他言語の演算子や存在しない関数を混在させる。"]',
     '["括弧、引用符、参照先、戻り値型、コンテキストを確認する。"]',
     75, 1, datetime('now')),
    ('naming-rules', 'FileMaker Naming Rules', '1.0.0',
     'FileMakerオブジェクトの一貫した命名規則。', 'convention',
     '["table","field","script","value_list","layout_object","database_design","relationship_design"]',
     '["Project固有の命名規則がある場合はそれを優先する。","用途と責務が分かる安定した名前を使用する。"]',
     '["患者__PK、診療__FK_患者"]',
     '["同一Project内で日本語名、略語、接頭辞の規則を無秩序に混在させる。"]',
     '["既存オブジェクトとの衝突と命名規則への適合を確認する。"]',
     65, 1, datetime('now')),
    ('vertex-validation-rules', 'VRTEX Validation Rules', '1.0.0',
     'VRTEXによる安全性・形式・ペースト可能性の検証規則。', 'validation',
     '["script","script_step","table","field","value_list","layout_object","database_design","relationship_design","review"]',
     '["AI生成物はClipboardへ送る前にParseとValidationを通す。","破壊的変更は自動適用せず警告と承認を要求する。"]',
     '["GeneratedからValidated、Ready、Copiedの状態を順に遷移させる。"]',
     '["AI応答を検証せずそのままFileMakerへ送信する。"]',
     '["XML構文、FileMaker形式、Project整合性、破壊的変更を個別に評価する。"]',
     98, 1, datetime('now')),
    ('relationship-design-rules', 'FileMaker Relationship Design', '1.0.0',
     'Relationship Designer向けのTO・Relationship設計知識。', 'design',
     '["database_design","relationship_design"]',
     '["Base TableとTable Occurrenceを区別する。","Relationshipの左右フィールドと演算子を明示する。"]',
     '["患者_TOと診療_TOを患者IDの等価条件で接続する。"]',
     '["同一のTOを無制限に多用途へ流用して文脈を曖昧にする。"]',
     '["TO参照、フィールド型、演算子、循環、孤立ノードを確認する。"]',
     82, 1, datetime('now'));
